/**
 * AGENTS.md generator (Codex target).
 *
 * Reads the Handlebars template from src/templates/agents-md.hbs and renders
 * it using the project's specops.yaml config. The output is written to
 * AGENTS.md at the project root.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Handlebars from "handlebars";
import type { SpecopsConfig } from "../config/schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

function templateDir(): string {
  const packageRoot = resolve(__dirname, "..", "..");
  return resolve(packageRoot, "src", "templates");
}

function registerHelpers(): void {
  // Re-register in case this module is loaded independently of claude-md.
  if (!Handlebars.helpers["inc"]) {
    Handlebars.registerHelper("inc", (value: number) => value + 1);
  }
}

/**
 * Generate AGENTS.md content from config.
 */
export async function renderAgentsMd(config: SpecopsConfig): Promise<string> {
  registerHelpers();

  const templatePath = resolve(templateDir(), "agents-md.hbs");
  const templateSource = await readFile(templatePath, "utf-8");
  const template = Handlebars.compile(templateSource, { noEscape: true });

  return template(config);
}

/**
 * Generate and write AGENTS.md to the project root.
 *
 * @param projectDir — Directory to write AGENTS.md into.
 * @param config — Parsed specops config.
 * @returns The absolute path of the generated file.
 */
export async function generateAgentsMd(
  projectDir: string,
  config: SpecopsConfig
): Promise<string> {
  const content = await renderAgentsMd(config);

  const notice = [
    "<!-- Generated by specops. Do not edit manually. Run `specops update` to regenerate. -->",
    "",
  ].join("\n");

  const outputPath = resolve(projectDir, "AGENTS.md");
  await writeFile(outputPath, notice + content, "utf-8");
  return outputPath;
}
