/**
 * CLAUDE.md generator.
 *
 * Reads the Handlebars template from src/templates/claude-md.hbs and renders
 * it using the project's specops.yaml config. The output is written to
 * CLAUDE.md at the project root.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Handlebars from "handlebars";
import type { SpecopsConfig } from "../config/schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Resolve the template directory. At runtime __dirname is dist/generators/,
 * so we walk up to the package root and look in src/templates/ (which is
 * shipped in the npm package via the "files" field).
 */
function templateDir(): string {
  const packageRoot = resolve(__dirname, "..", "..");
  return resolve(packageRoot, "src", "templates");
}

/**
 * Register Handlebars helpers used in the CLAUDE.md template.
 */
function registerHelpers(): void {
  // {{inc @index}} — output 1-based index
  Handlebars.registerHelper("inc", (value: number) => value + 1);

  // {{index_1 @index}} — same as inc, available as block helper
  Handlebars.registerHelper("index_1", (value: number) => value + 1);
}

/**
 * Generate CLAUDE.md content from config.
 */
export async function renderClaudeMd(config: SpecopsConfig): Promise<string> {
  registerHelpers();

  const templatePath = resolve(templateDir(), "claude-md.hbs");
  const templateSource = await readFile(templatePath, "utf-8");
  const template = Handlebars.compile(templateSource, { noEscape: true });

  return template(config);
}

/**
 * Generate and write CLAUDE.md to the project root.
 *
 * @param projectDir — Directory to write CLAUDE.md into.
 * @param config — Parsed specops config.
 * @returns The absolute path of the generated file.
 */
export async function generateClaudeMd(
  projectDir: string,
  config: SpecopsConfig
): Promise<string> {
  const content = await renderClaudeMd(config);

  // Prepend a generation notice
  const notice = [
    "<!-- Generated by specops. Do not edit manually. Run `specops update` to regenerate. -->",
    "",
  ].join("\n");

  const outputPath = resolve(projectDir, "CLAUDE.md");
  await writeFile(outputPath, notice + content, "utf-8");
  return outputPath;
}
